[workspace]
members = [
    "services/sdkwork-notes-product",
    "packages/native-rust/routes/app-api/sdkwork-routes-notes-app-api",
    "packages/native-rust/routes/backend-api/sdkwork-routes-notes-backend-api",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1"
axum = "0.7"
http = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "any", "sqlite"] }
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5", features = ["util"] }

sdkwork-notes-product = { path = "services/sdkwork-notes-product" }
sdkwork-routes-notes-backend-api = { path = "packages/native-rust/routes/backend-api/sdkwork-routes-notes-backend-api" }
