// @generated by tools/gen_http_route_manifest_from_json.py — do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/notes/ai_jobs",
        "notes",
        "aiJobs.admin.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/notes/ai_jobs/{ai_job_id}",
        "notes",
        "aiJobs.admin.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/notes/ai_jobs/{ai_job_id}/cancel",
        "notes",
        "aiJobs.cancel",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/notes/ai_jobs/{ai_job_id}/claim",
        "notes",
        "aiJobs.claim",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/notes/ai_jobs/{ai_job_id}/complete",
        "notes",
        "aiJobs.complete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/notes/ai_suggestions/{ai_suggestion_id}/accept",
        "notes",
        "aiSuggestions.accept",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/notes/ai_suggestions/{ai_suggestion_id}/reject",
        "notes",
        "aiSuggestions.reject",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/notes/ai_suggestions/{ai_suggestion_id}/apply",
        "notes",
        "aiSuggestions.apply",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/notes/ai_suggestions/{ai_suggestion_id}/feedback",
        "notes",
        "aiSuggestions.feedback.list",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
