[package]
name = "sdkwork-router-notes-backend-api"
version.workspace = true
edition.workspace = true

[lib]
name = "sdkwork_router_notes_backend_api"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork-notes-product.workspace = true
sqlx.workspace = true
tokio.workspace = true

[dev-dependencies]
async-trait.workspace = true
tower.workspace = true
