[package]
name = "sdkwork-router-notes-backend-api"
version.workspace = true
edition.workspace = true

[lib]
name = "sdkwork_router_notes_backend_api"
path = "src/lib.rs"

[dependencies]
sdkwork-database-config = { path = "../../../sdkwork-database/crates/sdkwork-database-config" }
axum.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork-notes-pages-service.workspace = true
sdkwork-router-notes-http-auth.workspace = true
sdkwork-web-core.workspace = true
sqlx.workspace = true
tokio.workspace = true

[dev-dependencies]
async-trait.workspace = true
sdkwork-notes-pages-repository-sqlx.workspace = true
tower.workspace = true
