#!/usr/bin/env python3
"""Generate http_route_manifest.rs from sdkwork route-manifest JSON."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

METHOD_MAP = {
    "GET": "Get",
    "POST": "Post",
    "PATCH": "Patch",
    "DELETE": "Delete",
    "PUT": "Put",
}

AUTH_MAP = {
    "dual-token": "dual_token",
    "api-key": "api_key",
    "public": "public",
}


def camel_to_snake(value: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()


def axum_path(openapi_path: str) -> str:
    def repl(match: re.Match[str]) -> str:
        return "{" + camel_to_snake(match.group(1)) + "}"

    return re.sub(r"\{([^}]+)\}", repl, openapi_path)


def render(routes: list[dict], fn_name: str) -> str:
    lines = [
        "// @generated by tools/gen_http_route_manifest_from_json.py — do not edit",
        "",
        "use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};",
        "",
        "const HTTP_ROUTES: &[HttpRoute] = &[",
    ]
    for route in routes:
        method = METHOD_MAP[route["method"]]
        path = axum_path(route["path"])
        tag = route["tags"][0]
        op = route["operationId"]
        auth_mode = route.get("auth", {}).get("mode", "dual-token")
        auth = AUTH_MAP.get(auth_mode, "dual_token")
        lines.extend(
            [
                f"    HttpRoute::{auth}(",
                f"        HttpMethod::{method},",
                f'        "{path}",',
                f'        "{tag}",',
                f'        "{op}",',
                "    ),",
            ]
        )
    lines.extend(
        [
            "];",
            "",
            f"pub fn {fn_name}() -> HttpRouteManifest {{",
            "    HttpRouteManifest::new(HTTP_ROUTES)",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: gen_http_route_manifest_from_json.py "
            "<route-manifest.json> <output.rs> <fn_name>",
            file=sys.stderr,
        )
        return 1

    manifest_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    fn_name = sys.argv[3]

    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    routes = data["routes"]
    if not routes:
        raise SystemExit(f"no routes in {manifest_path}")

    output_path.write_text(render(routes, fn_name), encoding="utf-8")
    print(f"wrote {len(routes)} routes to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
